//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 01:54:11 PM SGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://openadr.org/oadr-2.0b/2012/07", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openadr.oadr_2_0b._2012._07;
