//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 01:54:11 PM SGT 
//


package ietf.params.xml.ns.icalendar_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dateAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dateAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="WEEKDAY"/>
 *     &lt;enumeration value="HOLIDAY"/>
 *     &lt;enumeration value="EVERYDAY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dateAttributeType")
@XmlEnum
public enum DateAttributeType {


    /**
     * \u0093\u00fa\u0097j\u0093\u00fa\u0088\u00c8\u008aO.
     * 
     */
    WEEKDAY,

    /**
     * \u0093\u00fa\u0097j\u0093\u00fa.
     * 
     */
    HOLIDAY,

    /**
     * \u0096\u0088\u0093\u00fa.
     * 
     */
    EVERYDAY;

    public String value() {
        return name();
    }

    public static DateAttributeType fromValue(String v) {
        return valueOf(v);
    }

}
