//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 01:54:11 PM SGT 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for currentValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="currentValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}payloadFloat"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "currentValueType", propOrder = {
    "payloadFloat"
})
public class CurrentValueType {

    protected PayloadFloatType payloadFloat;

    /**
     * Gets the value of the payloadFloat property.
     * 
     * @return
     *     possible object is
     *     {@link PayloadFloatType }
     *     
     */
    public PayloadFloatType getPayloadFloat() {
        return payloadFloat;
    }

    /**
     * Sets the value of the payloadFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayloadFloatType }
     *     
     */
    public void setPayloadFloat(PayloadFloatType value) {
        this.payloadFloat = value;
    }

}
