//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 01:54:11 PM SGT 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalTypeExtTypeEnumeratedType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SignalTypeExtTypeEnumeratedType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ALLOWED_REVERSE_FLOW"/>
 *     &lt;enumeration value="NONE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SignalTypeExtTypeEnumeratedType")
@XmlEnum
public enum SignalTypeExtTypeEnumeratedType {


    /**
     * ALLOWED_REVERSE_FLOW.
     * 
     */
    ALLOWED_REVERSE_FLOW,

    /**
     * \u008ew\u0092\u00e8\u0082\u00c8\u0082É .
     * 
     */
    NONE;

    public String value() {
        return name();
    }

    public static SignalTypeExtTypeEnumeratedType fromValue(String v) {
        return valueOf(v);
    }

}
