//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 01:54:11 PM SGT 
//


package org.oasis_open.docs.ns.energyinterop._201110;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalNameEnumeratedType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SignalNameEnumeratedType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="SIMPLE"/>
 *     &lt;enumeration value="ELECTRICITY_PRICE"/>
 *     &lt;enumeration value="ENERGY_PRICE"/>
 *     &lt;enumeration value="DEMAND_CHARGE"/>
 *     &lt;enumeration value="BID_PRICE"/>
 *     &lt;enumeration value="BID_LOAD"/>
 *     &lt;enumeration value="BID_ENERGY"/>
 *     &lt;enumeration value="CHARGE_STATE"/>
 *     &lt;enumeration value="LOAD_DISPATCH"/>
 *     &lt;enumeration value="LOAD_CONTROL"/>
 *     &lt;enumeration value="DEMAND_DISCHARGE"/>
 *     &lt;enumeration value="DEMAND_FULL_DISCHARGE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SignalNameEnumeratedType")
@XmlEnum
public enum SignalNameEnumeratedType {


    /**
     * Simple levels (OpenADR 2.0a compliant)
     * 
     */
    SIMPLE,

    /**
     * This is the cost of electricity
     * 
     */
    ELECTRICITY_PRICE,

    /**
     * This is the cost of energy
     * 
     */
    ENERGY_PRICE,

    /**
     * This is the demand charge
     * 
     */
    DEMAND_CHARGE,

    /**
     * This is the price that was bid by the resource
     * 
     */
    BID_PRICE,

    /**
     * This is the amount of load that was bid by a resource into a program
     * 
     */
    BID_LOAD,

    /**
     * This is the amount of energy from a resource that was bid into a program
     * 
     */
    BID_ENERGY,

    /**
     * State of energy storage resource
     * 
     */
    CHARGE_STATE,

    /**
     * This is used to dispatch load
     * 
     */
    LOAD_DISPATCH,

    /**
     * Set load output to relative values
     * 
     */
    LOAD_CONTROL,

    /**
     * DEMAND_DISCHARGE.
     * 
     */
    DEMAND_DISCHARGE,

    /**
     * DEMAND_FULL_DISCHARGE.
     * 
     */
    DEMAND_FULL_DISCHARGE;

    public String value() {
        return name();
    }

    public static SignalNameEnumeratedType fromValue(String v) {
        return valueOf(v);
    }

}
