//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 01:54:11 PM SGT 
//


package org.oasis_open.docs.ns.emix._2011._06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.emix._2011._06.power.EnergyItemType;
import org.oasis_open.docs.ns.emix._2011._06.power.PowerItemType;
import org.oasis_open.docs.ns.emix._2011._06.power.VoltageType;
import org.openadr.oadr_2_0b._2012._07.BaseUnitType;
import org.openadr.oadr_2_0b._2012._07.CurrencyType;
import org.openadr.oadr_2_0b._2012._07.CurrentType;
import org.openadr.oadr_2_0b._2012._07.FrequencyType;
import org.openadr.oadr_2_0b._2012._07.OadrGBItemBase;
import org.openadr.oadr_2_0b._2012._07.PulseCountType;
import org.openadr.oadr_2_0b._2012._07.TemperatureType;
import org.openadr.oadr_2_0b._2012._07.ThermType;


/**
 * Abstract base type for units for EMIX Product delivery, measurement, and warrants.
 * 
 * <p>Java class for ItemBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemBaseType")
@XmlSeeAlso({
    TemperatureType.class,
    PulseCountType.class,
    CurrencyType.class,
    ThermType.class,
    FrequencyType.class,
    BaseUnitType.class,
    CurrentType.class,
    OadrGBItemBase.class,
    VoltageType.class,
    PowerItemType.class,
    EnergyItemType.class
})
public abstract class ItemBaseType {


}
